#!/bin/bash
#Paarsuse kontroll
#Kasutaja sisendi küsimine

echo -e "Sisesta arv: \c"
read arv

#Jäägi arvutamine

jaak=$(($arv % 2))

#Tingimus - kui jaak on null - arv on paaris

if test $jaak -eq 0
then
        echo "Antud arv on paaris"
else
        echo "Antud arv on paaritu"
fi
